services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
    environment:
      - URL_MONGO=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - db_net
  mongodb:
    image: mongo
    ports:
      - 27017:27017

    volumes:
      - ./data:/data/db
    networks:
      - db_net

  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm run start
    volumes:
      - ./client/src/:/app/src
    networks:
      - db_net

networks:
  db_net:
